spring:
  profiles: dev
Zxingpath: F:\ideaworkspace\tree\src\main\resources\static\zxing\
Picturepath: F:\ideaworkspace\tree\src\main\resources\static\zxing\picture\
zxingurl: localhost:9000/zxing/
pictureurl: localhost:9000/zxing/picture/
redis:
  host: 47.95.214.19
  port: 6379
  #连接超时时间
  timeout: 30000

  jedis:
    pool:
        #最大连接数,负数未没有限制
      max-active: 10
        #最大空闲数
      max-idle: 8
        #最大阻塞等待时间
      max-wait: -1
        #最小空闲连接
      min-idle: 0
