spring:
  profiles: prod
Zxingpath: /data/image/tree/zxing/
Picturepath: /data/image/tree/zxing/picture/
zxingurl: http://czhhzc.cn/image/tree/zxing/
pictureurl: http://czhhzc.cn/image/tree/zxing/picture/
redis:
  host: 127.0.0.1
  port: 6379
    #连接超时时间
  timeout: 30000

  jedis:
    pool:
        #最大连接数,负数未没有限制
      max-active: 10
        #最大空闲数
      max-idle: 8
        #最大阻塞等待时间
      max-wait: -1
        #最小空闲连接
      min-idle: 0
